name: website

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - 
        name: Change to Frontend directory
        run: cd front
      -
        name: Show Package.json file
        run: cat ./package.json
      -
        name: Yarn version
        run: yarn -v
      - 
        name: Install Node Dependencies
        run: yarn
      - 
        name: Build static files from jsx
        run: yarn build
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: front/dist
          ssh-key: ${{ secrets.DEPLOY_KEY }}
